name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: atluu315/Katalon_Studio_Github_Action@1.2
      with:
          version: '8.6.4'
          projectPath: './'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey= 7da4c3bf-f966-4203-a4d9-db4c7adf8809 --config -webui.autoUpdateDrivers=true'